consumes:
- application/app.metacontroller.v1+json
info:
  description: Webhook API for building Kubernetes controllers
  title: Metacontroller
  version: 0.3.0
paths: {}
produces:
- application/app.metacontroller.v1+json
schemes:
- http
swagger: "2.0"
