// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Metacontroller
Webhook API for building Kubernetes controllers


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.3.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
