// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Webhook API for building Kubernetes controllers",
    "title": "Metacontroller",
    "version": "0.3.0"
  },
  "paths": {
    "/finalize": {
      "post": {
        "operationId": "finalizeHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object"
                },
                "controller": {
                  "type": "object"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    true
                  ]
                },
                "parent": {
                  "type": "object"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "finalized": {
                  "type": "boolean"
                },
                "status": {
                  "type": "object"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    },
    "/sync": {
      "post": {
        "operationId": "syncHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object"
                },
                "controller": {
                  "type": "object"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    false
                  ]
                },
                "parent": {
                  "type": "object"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "status": {
                  "type": "object"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Webhook API for building Kubernetes controllers",
    "title": "Metacontroller",
    "version": "0.3.0"
  },
  "paths": {
    "/finalize": {
      "post": {
        "operationId": "finalizeHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object"
                },
                "controller": {
                  "type": "object"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    true
                  ]
                },
                "parent": {
                  "type": "object"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "finalized": {
                  "type": "boolean"
                },
                "status": {
                  "type": "object"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    },
    "/sync": {
      "post": {
        "operationId": "syncHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object"
                },
                "controller": {
                  "type": "object"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    false
                  ]
                },
                "parent": {
                  "type": "object"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "status": {
                  "type": "object"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    }
  }
}`))
}
