// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2018 The Knative Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Webhook API for building Kubernetes controllers",
    "title": "Metacontroller",
    "version": "0.3.0"
  },
  "paths": {
    "/finalize": {
      "post": {
        "operationId": "finalizeHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                      "$ref": "#/definitions/ContainerSource"
                    }
                  }
                },
                "controller": {
                  "$ref": "#/definitions/CompositeController"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    true
                  ]
                },
                "parent": {
                  "$ref": "#/definitions/KubernetesEventSource"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ContainerSource"
                  }
                },
                "finalized": {
                  "type": "boolean"
                },
                "status": {
                  "$ref": "#/definitions/KubernetesEventSourceStatus"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    },
    "/sync": {
      "post": {
        "operationId": "syncHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                      "$ref": "#/definitions/ContainerSource"
                    }
                  }
                },
                "controller": {
                  "$ref": "#/definitions/CompositeController"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    false
                  ]
                },
                "parent": {
                  "$ref": "#/definitions/KubernetesEventSource"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ContainerSource"
                  }
                },
                "status": {
                  "$ref": "#/definitions/KubernetesEventSourceStatus"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    }
  },
  "definitions": {
    "CompositeController": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "mcv1alpha1",
          "package": "metacontroller.app/apis/metacontroller/v1alpha1"
        },
        "type": "CompositeController"
      }
    },
    "Condition": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "ContainerSource": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "sourcesv1alpha1",
          "package": "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
        },
        "type": "ContainerSource"
      }
    },
    "DecoratorController": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "mcv1alpha1",
          "package": "metacontroller.app/apis/metacontroller/v1alpha1"
        },
        "type": "DecoratorController"
      }
    },
    "KubernetesEventSource": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        },
        {
          "properties": {
            "spec": {
              "$ref": "#/definitions/KubernetesEventSourceSpec"
            },
            "status": {
              "$ref": "#/definitions/KubernetesEventSourceStatus"
            }
          }
        }
      ]
    },
    "KubernetesEventSourceSpec": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string"
        },
        "serviceAccountName": {
          "type": "string"
        },
        "sink": {
          "$ref": "#/definitions/ObjectReference"
        }
      }
    },
    "KubernetesEventSourceStatus": {
      "type": "object",
      "properties": {
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Condition"
          }
        },
        "sinkURI": {
          "type": "string"
        }
      }
    },
    "Object": {
      "type": "object",
      "properties": {
        "apiVersion": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/ObjectMeta"
        }
      },
      "discriminator": "kind"
    },
    "ObjectMeta": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "metav1",
          "package": "k8s.io/apimachinery/pkg/apis/meta/v1"
        },
        "type": "ObjectMeta"
      }
    },
    "ObjectReference": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "corev1",
          "package": "k8s.io/api/core/v1"
        },
        "type": "ObjectReference"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Webhook API for building Kubernetes controllers",
    "title": "Metacontroller",
    "version": "0.3.0"
  },
  "paths": {
    "/finalize": {
      "post": {
        "operationId": "finalizeHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                      "$ref": "#/definitions/ContainerSource"
                    }
                  }
                },
                "controller": {
                  "$ref": "#/definitions/CompositeController"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    true
                  ]
                },
                "parent": {
                  "$ref": "#/definitions/KubernetesEventSource"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ContainerSource"
                  }
                },
                "finalized": {
                  "type": "boolean"
                },
                "status": {
                  "$ref": "#/definitions/KubernetesEventSourceStatus"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    },
    "/sync": {
      "post": {
        "operationId": "syncHook",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "required": [
                "finalizing"
              ],
              "properties": {
                "children": {
                  "type": "object",
                  "additionalProperties": {
                    "type": "object",
                    "additionalProperties": {
                      "$ref": "#/definitions/ContainerSource"
                    }
                  }
                },
                "controller": {
                  "$ref": "#/definitions/CompositeController"
                },
                "finalizing": {
                  "type": "boolean",
                  "enum": [
                    false
                  ]
                },
                "parent": {
                  "$ref": "#/definitions/KubernetesEventSource"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "children": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/ContainerSource"
                  }
                },
                "status": {
                  "$ref": "#/definitions/KubernetesEventSourceStatus"
                }
              }
            }
          },
          "default": {
            "description": "error"
          }
        }
      }
    }
  },
  "definitions": {
    "CompositeController": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "mcv1alpha1",
          "package": "metacontroller.app/apis/metacontroller/v1alpha1"
        },
        "type": "CompositeController"
      }
    },
    "Condition": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "ContainerSource": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "sourcesv1alpha1",
          "package": "github.com/knative/eventing-sources/pkg/apis/sources/v1alpha1"
        },
        "type": "ContainerSource"
      }
    },
    "DecoratorController": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "mcv1alpha1",
          "package": "metacontroller.app/apis/metacontroller/v1alpha1"
        },
        "type": "DecoratorController"
      }
    },
    "KubernetesEventSource": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        },
        {
          "properties": {
            "spec": {
              "$ref": "#/definitions/KubernetesEventSourceSpec"
            },
            "status": {
              "$ref": "#/definitions/KubernetesEventSourceStatus"
            }
          }
        }
      ]
    },
    "KubernetesEventSourceSpec": {
      "type": "object",
      "properties": {
        "namespace": {
          "type": "string"
        },
        "serviceAccountName": {
          "type": "string"
        },
        "sink": {
          "$ref": "#/definitions/ObjectReference"
        }
      }
    },
    "KubernetesEventSourceStatus": {
      "type": "object",
      "properties": {
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Condition"
          }
        },
        "sinkURI": {
          "type": "string"
        }
      }
    },
    "Object": {
      "type": "object",
      "properties": {
        "apiVersion": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "metadata": {
          "$ref": "#/definitions/ObjectMeta"
        }
      },
      "discriminator": "kind"
    },
    "ObjectMeta": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "metav1",
          "package": "k8s.io/apimachinery/pkg/apis/meta/v1"
        },
        "type": "ObjectMeta"
      }
    },
    "ObjectReference": {
      "type": "object",
      "x-go-type": {
        "import": {
          "alias": "corev1",
          "package": "k8s.io/api/core/v1"
        },
        "type": "ObjectReference"
      }
    }
  }
}`))
}
