# apiVersion: serving.knative.dev/v1alpha1
# kind: Service
# metadata:
#   name: k8s-sources-controller
#   namespace: knative-sources
# spec:
#   runLatest:
#     configuration:
#       revisionTemplate:
#         spec:
#           container:
#             image: github.com/grantr/k8s-source/cmd/k8ssource-server
