# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: k8s-sources-controller-role
# rules:
# - apiGroups:
#   - sources.eventing.knative.dev
#   resources:
#   - containersources
#   verbs:
#   - get
#   - list
#   - watch
#   - create
#   - update
# - apiGroups:
#   - sources.eventing.knative.dev
#   resources:
#   - kuberneteseventsources
#   verbs:
#   - get
#   - list
#   - watch
#   - update
#
# ---
#
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: k8s-sources-controller
#   namespace: knative-sources
#
# ---
#
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: k8s-sources-controller-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: k8s-sources-controller-role
# subjects:
# - kind: ServiceAccount
#   name: k8s-sources-controller
#   namespace: knative-sources
